"""remove tag_id from recipe

Revision ID: 3b24ff3ecfc5
Revises: 7ffe35ae768d
Create Date: 2024-06-05 19:00:29.667388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b24ff3ecfc5'
down_revision = '7ffe35ae768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_tag_id_tags', type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_tag_id_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
