"""autogenerate messsage

Revision ID: 9c7b7fe4b7fb
Revises: cf98cc70af99
Create Date: 2024-06-14 13:20:11.259663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7b7fe4b7fb'
down_revision = 'cf98cc70af99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_user', sa.String(length=255), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('photo_user')

    # ### end Alembic commands ###
